In [2]:
import torch
import numpy as np
print(torch.cuda.is_available())

False


/home/f/Documents/projects-local/learning_ai/tutorials/.venv/lib/python3.11/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0


In [3]:
data = [[1,2], [1,2]]
x_data = torch.tensor(data)
print(data)
print(x_data)

[[1, 2], [1, 2]]
tensor([[1, 2],
        [1, 2]])


In [24]:
#bridge NumPy array to tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
backtonp = x_np.numpy() #I assume .detach().cpu().numpy is if the tensor is in some kind of chain?

print(np_array)
print(x_np)
print(backtonp)

[[1 2]
 [1 2]]
tensor([[1, 2],
        [1, 2]])
[[1 2]
 [1 2]]


In [16]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

x_rand = torch.rand_like(x_data, dtype=torch.double)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7731, 0.7653],
        [0.1304, 0.3925]]) 

Random Tensor: 
 tensor([[0.4245, 0.5537],
        [0.9673, 0.7593]], dtype=torch.float64) 



In [21]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
altones_tensor = torch.ones_like(ones_tensor)
zeros_tensor = torch.zeros(shape)

print(f"(Random Tensor:\n{rand_tensor}\n")
print(f"(Ones Tensor:\n{ones_tensor}\n")
print(f"(Ones (alt) Tensor:\n{altones_tensor}\n")
print(f"(Zeros Tensor:\n{zeros_tensor}")

(Random Tensor:
tensor([[0.8326, 0.4975, 0.6391],
        [0.7954, 0.9574, 0.7578]])

(Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

(Ones (alt) Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

(Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
tensor = torch.rand(3,4)
print(f"Tensor shape: {tensor.shape}")
print(f"Tensor data type: {tensor.dtype}")
print(f"Tensor stored on device: {tensor.device}")

Tensor shape: torch.Size([3, 4])
Tensor data type: torch.float32
Tensor stored on device: cpu


In [26]:
#tensor = torch.rand(4,4)
tensor = torch.ones(4,4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0) #why does this have to be in range [-2, 1]?
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
#elementwise product
print(f"tensor.mul(tensor) \n{tensor.mul(tensor)} \n") #function call off tensor object
print(f"tensor*tensor\n{tensor * tensor}") #operator on tensor objects

tensor.mul(tensor) 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor*tensor
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [29]:
#matrix mult
tensor.matmul(tensor.T)
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [31]:
print(tensor, "\n")
tensor.add_(5) #"in-place" operations are per-element of tensor. Can cause issues with derivatives
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [33]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(n)

t: tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [34]:
#changes to numpy reflect in tensor?
n = np.ones(5)
t = torch.from_numpy(n)

In [36]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]


In [37]:
#do changes in tensor reflect in numpy? --> yes
t.sub_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
