In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [12]:
print(data)

tensor([[[[0.7842, 0.0738, 0.3700,  ..., 0.9668, 0.2265, 0.6333],
          [0.8981, 0.5064, 0.1614,  ..., 0.2018, 0.8981, 0.5098],
          [0.5348, 0.1774, 0.4883,  ..., 0.2150, 0.2752, 0.5883],
          ...,
          [0.5945, 0.8046, 0.3049,  ..., 0.4919, 0.6924, 0.6369],
          [0.6111, 0.2541, 0.8189,  ..., 0.5144, 0.3597, 0.6668],
          [0.7220, 0.4291, 0.3643,  ..., 0.7128, 0.6856, 0.6774]],

         [[0.1908, 0.0045, 0.4513,  ..., 0.2460, 0.5023, 0.8190],
          [0.1372, 0.3499, 0.5998,  ..., 0.6069, 0.7403, 0.6977],
          [0.2922, 0.6138, 0.7267,  ..., 0.3186, 0.7350, 0.0305],
          ...,
          [0.3361, 0.0777, 0.2720,  ..., 0.7435, 0.5143, 0.6868],
          [0.0201, 0.4985, 0.4782,  ..., 0.2485, 0.7698, 0.9455],
          [0.9912, 0.5761, 0.9809,  ..., 0.1384, 0.0525, 0.2193]],

         [[0.0680, 0.9949, 0.4869,  ..., 0.1191, 0.7303, 0.7646],
          [0.3163, 0.5226, 0.1027,  ..., 0.5539, 0.8621, 0.8440],
          [0.8876, 0.8957, 0.9525,  ..., 0

In [29]:
prediction = model(data) #send random image through model

In [30]:
#compute how much model output deviates from the randomly generated labels
loss = (prediction - labels).sum()
loss.backward()
print(loss)

tensor(-1178711.3750, grad_fn=<SumBackward0>)


In [31]:
#load stochastic gradient descent algo to adjust model parameters based on loss fn/backprop
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [32]:
#step initiates gradient descent step
optim.step()

In [40]:
#autograd:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 - b**2

In [41]:
#tensor has a .backward() function that computes gradient (partial deriv of each input, and stores result of current value in .grad tensor attribute
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

print(9*a**2 == a.grad)
print(-2*b == b.grad)
print(external_grad)

tensor([True, True])
tensor([True, True])
tensor([1., 1.])


In [43]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5,5), requires_grad=True)

a=x+y
print(f"Does 'a' require gradients?: {a.requires_grad}")
b = x+z
print(f"Does 'b' require gradients: {b.requires_grad}")

Does 'a' require gradients?: False
Does 'b' require gradients: True


In [46]:
from torch import nn, optim
model = resnet18(weights=ResNet18_Weights.DEFAULT)

for param in model.parameters():
    param.requires_grad = False #freeze all the parameters

#resent: classifier is last linear layer model.fc; add a new unfrozen linear layer to act as classifier
model.fc = nn.Linear(512, 10)

#optimize only the classifier:
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optimizer.step()